version: "2"
services:
  django:
    container_name: django_server
    build:
      context: ./backend/src/
      dockerfile: Dockerfile
    image: docker_tutorial_django
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/myproject
    ports:
      - "8000:8000"
    