# Generated by Django 2.2.4 on 2019-09-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
